### ISSUE TITLE
REST API definition with query params fails to compile on Lispworks

### ISSUE THREAD

**Issue by JukkaOravasaari** [bonkzwonil/defrest#8]
Putting the below API definition into a .lisp file and attempt to compile into .64ufasl on Lispworks fails:

```
(defrest "/songs/{album-id:[0-9]+}" :GET (album-id :query offset limit)
        (get-songs album-id offset limit))
```
error: Object #<Closure 1 subfunction of DEFREST::CREATE-QUERY-PARAM-PARSER 4050001B74> is of type FUNCTION which is not externalizable to #<STREAM::LATIN-1-FILE-STREAM /t_server.64ufasl>.

Compilation failed.

**Comment by bonkzwonil** [comment]
Fixed in master thanks to #7
